2nd homework
chaoticsparks/EPAM-oop-algo-homework pull request #1
Opened 2021-04-15 11:11 UTC by chaoticsparks

2021-04-16 09:45 UTC, dctenna requested changes

2021-04-16 09:45 UTC, dctenna commented on 02_oop_part_1/code/src/Inventory.ts
> +  private items: Item[];
Please, assign empty array for items.

2021-04-16 10:06 UTC, chaoticsparks commented on 02_oop_part_1/code/src/Inventory.ts
> +  private items: Item[];
done!

2021-04-19 07:32 UTC, dctenna approved these changes

2021-04-26 07:59 UTC, merged